### ISSUE TITLE
Hinweise zum Python Webhosting

### ISSUE THREAD

**Issue by cyroxx** [saschaszott/saschaszott.github.io#1]
Hi @saschaszott!

Vielen Dank für deinen Blogpost, der hat mir den ein oder anderen Stolperstein genommen ;)
Zu deinen offenen Punkten:

## 1. Python-Pakete/venv synchronisieren
Ich habe es so gelöst, dass ich die ganze `venv` kopiere und anschließend in meiner `passenger_wsgi.py` den Pfad erweitere, damit Python die Pakete in `site-packages` findet.

Also erst
```scp -r venv hostingXXX@188.XXX.XXX.XXX:/flask-app```
und dann in der `passenger_wsgi.py`:
```
import sys
sys.path.append('./venv/lib/python3.5/site-packages')
...
from myapp import app
```

Das ist in meinen Augen eine stabilere Lösung. Man kann da wahrscheinlich noch optimieren ([How can I best copy large numbers of small files over scp?](https://unix.stackexchange.com/questions/10026/how-can-i-best-copy-large-numbers-of-small-files-over-scp)), aber die Idee wird erstmal klar.

## 2. Warum enthält die `venv` Pakete wie `setuptools`?
Der Grundgedanke der `venv` ist ja, dass du eine leere, saubere Umgebung hast. Damit du aber mit pip & Co. einfach Pakete installieren kannst, werden u.a. `setuptools` installiert.

**Comment by saschaszott** [comment]
Hallo @cyroxx , danke für die Hinweise!

**Comment by saschaszott** [comment]
Ich habe deine Hinweise in den Blogpost aufgenommen. Dieses Ticket schließe ich daher.
